version: "3.8"

services:

  ltl_api:
    build:
      context: ../API
      dockerfile: api.dockerfile
    depends_on:
      - mongo
    container_name: ltl_api
    env_file:
      - .env
    environment:
      APP_MODE: Development
    ports:
      - "8090:8000"
    volumes:
      - ../API:/LittleAPI
    networks:
      - tarot_net
    command: python3 main.py


  mongo:
    image: mongo
    container_name: '${MONGO_HOST}'
    ports:
      - "27001:27001"
    volumes:
      - ./Data/Mongo/:/data/db
    env_file: .env
    networks:
      - tarot_net
    command: mongod --quiet --logpath /dev/null --port 27001

  web:
    image: node:19-alpine
    container_name: LittleReact
    ports:
      - "80:80"
    depends_on:
      - ltl_api
      - mongo
    volumes:
      - ../web:/web
      - exclude:/web/node_modules
    working_dir: /web
    env_file: .env
    networks:
      - tarot_net
    command: sh -c "echo "VITE_API_ROOT=${DEV_API_ENDPOINT}" > .env.development && npm i && npm run dev -- --port 80 --host 0.0.0.0;"

  redis:
    image: redis:latest
    container_name: TarotRedis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASS:?REDIS_PASS variable is not set} --save 20 1 --loglevel warning --port ${REDIS_PORT}
    volumes:
      - ./Data/Redis:/data
    networks:
      - tarot_net


networks:
  tarot_net:
    driver: bridge

volumes:
    exclude: